# Generated by Django 3.1.1 on 2020-09-10 07:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=254)),
                ('nom', models.CharField(max_length=254)),
                ('area', models.FloatField()),
                ('population', models.FloatField()),
                ('pop_den', models.FloatField()),
                ('tot_death_field', models.BigIntegerField()),
                ('tot_infect', models.BigIntegerField()),
                ('death_rate', models.FloatField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
